# Generated by Django 5.2.8 on 2025-12-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, help_text='URL da imagem do post no Cloudinary.', max_length=500, null=True),
        ),
    ]
