# Generated by Django 5.2.8 on 2025-12-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='URL da foto de perfil do usuário no Cloudinary.', max_length=500, null=True),
        ),
    ]
